var Constants = {
    homepage: {
        ngos: [{
                ngo_id: 'ngo1',
                ngo_name: 'UNESCO',
                cause_id: 'xyz',
                logo_url: 'https://media.boingboing.net/wp-content/uploads/2017/04/eee3503c894be321f31a99d1294ccd7b.jpg'
            },
            {
                ngo_id: 'ngo2',
                ngo_name: 'CRY',
                cause_id: 'xyz',
                logo_url: 'https://www.lawctopus.com/wp-content/uploads/2013/09/cry.jpg'
            },
            {
                ngo_id: 'ngo3',
                ngo_name: 'Joel',
                cause_id: 'xyz1',
                logo_url: 'https://www.lawctopus.com/wp-content/uploads/2013/09/cry.jpg'
            },
            {
                ngo_id: 'ngo4',
                ngo_name: 'MPK',
                cause_id: 'xyz1',
                logo_url: 'https://www.lawctopus.com/wp-content/uploads/2013/09/cry.jpg'
            },
            {
                ngo_id: 'ngo4',
                ngo_name: 'oeodv',
                cause_id: 'xyz1',
                logo_url: 'https://www.lawctopus.com/wp-content/uploads/2013/09/cry.jpg'
            },
            {
                ngo_id: 'ngo6',
                ngo_name: 'Anupama',
                cause_id: 'xyz',
                logo_url: 'https://www.lawctopus.com/wp-content/uploads/2013/09/cry.jpg'
            },
            {
                ngo_id: 'tbs',
                ngo_name: 'Tarun Bharat Sangh',
                logo_url: 'https://www.lawctopus.com/wp-content/uploads/2013/09/cry.jpg'
            },
            {
                ngo_id: 'hhk',
                ngo_name: 'Har Haath Kalam',
                logo_url: 'https://www.lawctopus.com/wp-content/uploads/2013/09/cry.jpg'
            },
            {
                ngo_id: 'aarambh',
                ngo_name: 'Aarambh',
                logo_url: 'https://www.lawctopus.com/wp-content/uploads/2013/09/cry.jpg'
            },
            {
                ngo_id: 'lol',
                ngo_name: 'Liter of Light',
                logo_url: 'https://www.lawctopus.com/wp-content/uploads/2013/09/cry.jpg'
            }
        ],
        stats: { donations: 'Rs. 11,134', followers: 6 },
        blogs: [{
                blog_id: 'mall',
                blog_title: 'Case of Mallika',
                title_photo_url: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                blog_short_desc: 'This is some small text at least put some long shit here'
            },
            {
                blog_id: 'taykath',
                blog_title: 'Nerd Writing shiiiiit',
                title_photo_url: 'https://assets.awwwards.com/awards/media/cache/optimize/submissions/2017/08/59914f216d820.jpg',
                blog_short_desc: 'Akjljl lkjlkj ljklkj re you the one who saves me Grafually watermelon WHAT TAYLOR SWIGFTJOEL OF JOEL of Joel'
            }
        ],
        projects: [{
                projectId: 'project-helpdesk',
                isFeatured: false,
                showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524391803/UI%20images/AARAMBH_squaere_3x.png',
                ngoId: 'aarambh',
                fullFeaturePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524373961/UI%20images/Webp.net-resizeimage.png',
                playPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031637/UI%20images/AARAMBH_play_1_2x.png',
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524581678/UI%20images/AARAMBH_Big_1_Copy_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031005/UI%20images/AARAMBH_Small_1_2x.png',
                cardStyle: 'background: radial-gradient(circle, #542A1A 0%, #301409 100%); color:white',
                projectTitle: 'Build School Helpdesks',
                featureActionTitle: 'Build School Helpdesks',
                forByLine: 'For 1200 Children',
                autoActionMessage: 'Open new tabs to do something something',
                tabsForSingleUnit: 200,
                actionTitle: 'Build<br>School<br>Helpdesks',
                homeDescription: 'Kids in rural India walk miles to reach the nearest school, often carrying their books in thin plastic bags. In theschool, they often sit on the floor without the aid of desks. Over time, this leads to poor posture, eyesight problems and even bad handwriting. Aarambh, a Mumbai based NGO, developed Helpdesk, which is a portable desk and school bag made out of recycled cardpaper. Also, the manufacturing of Helpdesks provides employment to the youth of these villages. Flutur has partnered with Aarambh to distribute more Helpdesks, so that every child has a school bag and a desk to study on.',
                shortDescription: 'Aarambh, a Mumbai based NGO, developed Helpdesk, which is a portable desk and school bag made out of recycled cardpaper. Helpdesks alleviate the postural issues and eyesight problems of young kids, who have to sit on the floor without a desk in rural India.',
                unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524391491/UI%20images/AARAMBH_tiny.png',
                currentUnitMeasure: 'desk',
                donateThanks: 'Thanks for helping Aarambh reach out to 1434 children',
                conversionFormula: '/119',
                donateFTUE: [Object],
                ngo: [Object],
                weeklyTargetTabs: 250
            },
            {
                projectId: 'project-hhk',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524397345/UI%20images/HHK_Big_1_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
                showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524391816/UI%20images/HHK_squaere_3x.png',
                ngoId: 'hhk',
                fullFeaturePhoto: 'https://res.cloudinary.com/epicfoundation/image/upload/v1523669576/dfd_gzbont.jpg',
                cardStyle: 'background: linear-gradient(254.64deg, #FFEEF7 0%, #FFCAE5 100%); color:black',
                playPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031667/UI%20images/HHK_play_1_2x.png',
                unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524581676/UI%20images/HHK_tiny.png',
                projectTitle: 'Create Low Cost Sanitary Pads',
                featureActionTitle: 'Create Low Cost Sanitary Pads',
                tabsForSingleUnit: 20,
                actionTitle: 'Supply<br>Low Cost<br>Sanitary Pads',
                forByLine: 'To 210 Women',
                donateThanks: 'Thanks for helping women women reach out to 1434 villagers',
                conversionFormula: '/0.7',
                currentUnitMeasure: 'napkin',
                homeDescription: 'Over 80% of menstruating women in rural India use un-sanitised cloth, ashes and husk sand. This leads to various diseases such as cervical cancer, uterus infection and skin cancer. Incidents of reproductive tract infection is an alarming 70% more common among these women. Har Hath Kalam (HHK) is an NGO that is on a mission is to create awareness against such unhygienic menstruation practices. HHK manufactures low cost, biodegradable, ultra thin sanitary napkins and distributes the napkins in medical centers across villages in North India. Flutur supports the HHK mission by donating sanitary napkins',
                shortDescription: 'Over 80% of menstruating women in rural India resort to unhygienic practices such as using un-sanitised cloth, ashes and husk sand. Har Hath Kalam (HHK) is an NGO that is on a mission is to create awareness against such unhygienic menstruation practices. HHK manufactures low cost, biodegradable, ultra thin sanitary napkins and distributes the napkins in medical centers across villages in NorthIndia.',
                ngo: [Object],
                donateFTUE: [Object],
                weeklyTargetTabs: 250
            },
            {
                projectId: 'project-lol',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031026/UI%20images/LOL_Big_1_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031025/UI%20images/LOL_Small_1_Copy_2_2x.png',
                showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524391821/UI%20images/LOL_squaere_3x.png',
                ngoId: 'lol',
                fullFeaturePhoto: 'https://res.cloudinary.com/epicfoundation/image/upload/v1523669576/dfd_gzbont.jpg',
                cardStyle: 'background:black;color:white',
                unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524391724/UI%20images/LOL_tiny.png',
                conversionFormula: '/50',
                tabsForSingleUnit: 200,
                forByLine: 'For 2100 Families',
                projectTitle: 'Light Rural Homes',
                featureActionTitle: 'Light Rural Homes',
                actionTitle: 'Light<br>Rural<br>Homes',
                homeDescription: 'Even today, over 240 million Indians do not have access to electricity. Several Government programs tried to address the issue, but a large number vulnerable, poor citizens of the country still have received little to no relief to their woes. Liter of Light Bangalore chapter is providing such households access to low cost, solar eco-friendly bottle bulbs. These solar powered bulbs provide illumination even during the night. Till date, it has illuminated over 2000 homes across India. Flutur has partnered with Liter of Light Bangalorechapter to illuminate one home at a time.',
                shortDescription: 'Over 240 million Indias do not have access to electricity. Liter of Light Bangalore chapter is providing such households access to low cost, solar eco-friendly bottle bulbs. These solar powered bulbs provide illumination even during the night.',
                playPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031695/UI%20images/LOL_play_1_2x.png',
                donateThanks: 'Thanks for helping LOL reach out to 1434 villagers',
                currentUnitMeasure: 'lamp',
                autoActionMessage: 'sdasd sdsad sd asd sd adadad dsad d',
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                ngo: [Object]
            }
        ],
        featuredProject: {
            projectId: 'project-tbs',
            isFeatured: true,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524397346/UI%20images/TBH_Big_1_2x.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031037/UI%20images/TBH_Big_1_2x.png',
            showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524391830/UI%20images/TBH_squaere_3x.png',
            fullFeaturePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524392631/UI%20images/Webp.net-resizeimage_3.png',
            ngoId: 'tbs',
            playPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031716/UI%20images/TBH_play_1_2x.png',
            unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524391491/UI%20images/TBH_tiny.png',
            tabsForSingleUnit: 6,
            projectTitle: 'Provide Access To Water',
            featureActionTitle: 'Provide Access To Water',
            forByLine: 'To 500 Villagers',
            actionTitle: 'Provide<br>Access To<br>Water',
            homeDescription: 'Karauli district is amongst the 100 most backward districts in India. Due to falling groundwater levels, productivityof agriculture and livestock rearing have fallen drastically. Frequent droughts have added to the plight of the people. To recharge ground water and restore ecology of Karauli, Tarun Bharat Sangh (TBS) is building 60 rainwater harvesting structures in the district. This would increase the income of each household by 150%. Flutur is contributing, albeit in small way, by raising funds for the project. Till date, TBS has built over 450 rainwater harvesting structures across 1,200 semi-arid villages in Rajasthan.',
            shortDescription: 'Karauli district is amongst the most backward districts in India. Due to falling groundwater levels, productivity ofagriculture and livestock rearing have further fallen drastically. Frequent droughts have added to the plight of the people. To recharge ground water and restore ecology of Karauli, Tarun Bharat Sangh (TBS) is building 60 rainwater harvesting structures in the district. Flutur is contributing in small way, by raising funds for the project.',
            donateThanks: 'Thanks for helping TBS make water! SOme longer thing here eve nlonger teere you go.Thanks for helping TBS make water! SOme longer thing here eve nlonger teere you go.Thanks for helping TBS make water! SOme longer thing here eve nlonger teere you go',
            cardStyle: 'background: radial-gradient(circle, #FFFFFF 0%, #FFFFFF 71.54%, #EEEEEE 100%); color:black',
            conversionFormula: '/6',
            autoActionMessage: 'Open new tabs to dfdsfs sfdf  dsfsdf dsf sdf',
            currentUnitMeasure: 'liter',
            donateFTUE: {
                title: 'Donate water by tabbing',
                info: 'somestuff about donation'
            },
            weeklyTargetTabs: 250,
            ngo: {
                ngoName: 'Tarun Bharat Sangh',
                ngoUrl: 'http://tarunbharatsangh.in/#',
                ngoPhotoUrl: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524396353/UI%20images/TBH_logo_2x.png'
            }
        }
    },
    project: {
        details: {
            projectId: 'project-hhk',
            projectTitle: 'HHK',
            isFeatured: false,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523498950/Artboard_2_hcz8kb.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/c_crop,h_740/v1523957184/HHK1_3x_a80oct.png',
            showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            ngoId: 'hhk',
            featureActionTitle: 'Create Eco-friend Sanitary-pads',
            actionTitle: 'Create<br>Eco-friendly<br>Sanitary-pads',
            homeDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such means during menstruation which are potentially harmful.',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such meansduring menstruation which are potentially harmful....',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 51,
            donateThanks: 'Thanks for helping women women reach out to 1434 villagers',
            conversionFormula: '/0.7',
            currentUnitMeasure: 'napkin',
            ngo: {
                ngoName: 'HHK',
                ngoUrl: 'http://www.aarambh.org/',
                ngoPhotoUrl: 'http://www.aarambh.org/images/logo.jpg'
            },
            donateFTUE: {
                title: 'Donate napkins by tabbing',
                info: 'somestuff about donation'
            },
            weeklyTargetTabs: 250
        },
        stats: { donations: 'Rs. 11,086', followers: 4 }
    },
    moveon: {

        projects: [{

                projectId: 'project-helpdesk',
                projectTitle: 'Helpdesks',
                isFeatured: false,
                showcasePhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT55IEoispK7mRRkBkQrblJRWWQBuFCPevVGA12QitxjVUg_zKN_g',
                ngoId: 'aarambh',
                featureActionTitle: 'Build School Helpdesks',
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957196/Artboard_2_3x_fv3di4.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/c_crop,h_740/v1523957953/Artboard_2_3x_t1zbqi.png',
                actionTitle: 'Build<br>School<br>Helpdesks',
                homeDescription: 'Aarambh stuffff sdfdfsdf dlkjfsdlfjd lsjs dfkjsdlf is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting hea...',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awar...',
                unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957194/aarambh_3x_nmwmwl.png',
                currentUnits: 5,
                currentUnitMeasure: 'desk',
                donateThanks: 'Thanks for helping Aarambh reach out to 1434 children',
                conversionFormula: '/119',
                donateFTUE: [Object],
                ngo: [Object],
                weeklyTargetTabs: 250,
                unitString: '5 desks'
            },
            {

                projectId: 'project-hhk',
                projectTitle: 'HHK',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523498950/Artboard_2_hcz8kb.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/c_crop,h_740/v1523957184/HHK1_3x_a80oct.png',
                showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                ngoId: 'hhk',
                featureActionTitle: 'Create Eco-friend Sanitary-pads',
                actionTitle: 'Create<br>Eco-friendly<br>Sanitary-pads',
                homeDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with...',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awar...',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 51,
                donateThanks: 'Thanks for helping women women reach out to 1434 villagers',
                conversionFormula: '/0.7',
                currentUnitMeasure: 'napkin',
                ngo: [Object],
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                unitString: '51 napkins'
            },
            {

                projectId: 'project-lol',
                projectTitle: 'Liter of Light',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523499284/Artboard_2_hcz8kb.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/c_crop,h_740/v1523499284/Artboard_2_hcz8kb.png',
                showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                ngoId: 'lol',
                featureActionTitle: 'Provide Buld Lights',
                actionTitle: 'Provide<br>Bulb<br>Lights',
                homeDescription: 'Liter of lights sdfdslkjdf skdjfdklsfj) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and di...',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awar...',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 2,
                conversionFormula: '/50',
                donateThanks: 'Thanks for helping LOL reach out to 1434 villagers',
                currentUnitMeasure: 'lamp',
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                ngo: [Object],
                unitString: '2 lamps'
            }
        ],
        featuredProject: {

            projectId: 'project-tbs',
            projectTitle: 'Tarun Bharat Sangh',
            isFeatured: true,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523771594/TBH_2_emxbyv.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957647/aaaq_yww14i.png',
            showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            ngoId: 'tbs',
            featureActionTitle: 'Help Rajasthan With Water',
            actionTitle: 'Help<br>Rajasthan<br>With Water',
            homeDescription: 'Waterman is dfsdff fdsfd fsfslhlks an NGO whose primary mission is to create awareness against begging, molding childbeggars towards by providing them with education, assisting healthy and disabled b...',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awar...',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 12,
            donateThanks: 'Thanks for helping TBS make water!',
            conversionFormula: '/100',
            currentUnitMeasure: 'project',
            donateFTUE: {
                title: 'Donate water by tabbing',
                info: 'somestuff about donation'
            },
            weeklyTargetTabs: 250,
            ngo: {
                ngoName: 'TBS',
                ngoUrl: 'http://www.aarambh.org/',
                ngoPhotoUrl: 'http://www.aarambh.org/images/logo.jpg'
            },
            unitString: '12 projects'
        },
        causes: [{

                cause_name: 'BITCH\'s Env Mission',
                cause_id: 'la',
                total_hearts: 100,
                img_url: 'http://res.cloudinary.com/epicfoundation/image/upload/v1511618893/epic_dog_zn3qfr.png',
                __v: 0,
                character: [Object],
                user_progress: 202
            }, {
                cause_name: 'Rah\'s Env Mission',
                cause_id: 'x1yz',
                total_hearts: 100,
                img_url: 'http://res.cloudinary.com/epicfoundation/image/upload/v1511864594/same_size_woman_cyat2i.png',
                __v: 0,
                character: [Object],
                user_progress: 2552
            },
            {

                cause_name: 'mallika\'s Env Mission',
                cause_id: 'xyz',
                total_hearts: 100,
                img_url: 'http://res.cloudinary.com/epicfoundation/image/upload/v1511864593/same_size_child_fvj6ca.png',
                __v: 0,
                character: [Object],
                user_progress: 656
            }
        ]
    },
    choosehhk: {
        projects: [{
                projectId: 'project-helpdesk',
                projectTitle: 'Helpdesks',
                isFeatured: false,
                showcasePhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT55IEoispK7mRRkBkQrblJRWWQBuFCPevVGA12QitxjVUg_zKN_g',
                ngoId: 'aarambh',
                featureActionTitle: 'Build School Helpdesks',
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957196/Artboard_2_3x_fv3di4.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031005/UI%20images/AARAMBH_Small_1_2x.png',
                actionTitle: 'Build<br>School<br>Helpdesks',
                cardStyle: 'background: radial-gradient(circle, #542A1A 0%, #301409 100%); color:white',
                homeDescription: 'Aarambh stuffff sdfdfsdf dlkjfsdlfjd lsjs dfkjsdlf is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting hea . . .',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
                unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957194/aarambh_3x_nmwmwl.png',
                currentUnits: 5,
                currentUnitMeasure: 'desk',
                donateThanks: 'Thanks for helping Aarambh reach out to 1434 children',
                conversionFormula: '/119',
                donateFTUE: [Object],
                ngo: [Object],
                weeklyTargetTabs: 250,
                unitString: '5 desks'
            },
            {
                projectId: 'project-tbs',
                projectTitle: 'Tarun Bharat Sangh',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031037/UI%20images/TBH_Small_1_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031037/UI%20images/TBH_Small_1_2x.png',
                showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                ngoId: 'tbs',
                featureActionTitle: 'Help Rajasthan With Water',
                actionTitle: 'Help<br>Rajasthan<br>With Water',
                homeDescription: 'Waterman is dfsdff fdsfd fsfslhlks an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled b . . .',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 12,
                donateThanks: 'Thanks for helping TBS make water!',
                cardStyle: 'background: radial-gradient(circle, #FFFFFF 0%, #FFFFFF 71.54%, #EEEEEE 100%); color:black',
                conversionFormula: '/100',
                currentUnitMeasure: 'project',
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                ngo: [Object],
                unitString: '12 projects'
            },
            {
                projectId: 'project-lol',
                projectTitle: 'Liter of Light',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031026/UI%20images/LOL_Big_1_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031025/UI%20images/LOL_Small_1_Copy_2_2x.png',
                showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                ngoId: 'lol',
                featureActionTitle: 'Provide Buld Lights',
                actionTitle: 'Provide<br>Bulb<br>Lights',
                cardStyle: 'background:black;color:white',
                homeDescription: 'Liter of lights sdfdslkjdf skdjfdklsfj) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and di . . .',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 2,
                conversionFormula: '/50',
                donateThanks: 'Thanks for helping LOL reach out to 1434 villagers',
                currentUnitMeasure: 'lamp',
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                ngo: [Object],
                unitString: '2 lamps'
            }
        ],
        featuredProject: {
            projectId: 'project-hhk',
            projectTitle: 'HHK',
            isFeatured: true,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Big_1_2x.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
            showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
            ngoId: 'hhk',
            featureActionTitle: 'Create Eco-friend Sanitary-pads',
            actionTitle: 'Create<br>Eco-friendly<br>Sanitary-pads',
            cardStyle: 'background: linear-gradient(254.64deg, #FFEEF7 0%, #FFCAE5 100%); color:black',
            homeDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with . . .',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 51,
            donateThanks: 'Thanks for helping women women reach out to 1434 villagers',
            conversionFormula: '/0.7',
            currentUnitMeasure: 'napkin',
            ngo: {
                ngoName: 'HHK',
                ngoUrl: 'http://www.aarambh.org/',
                ngoPhotoUrl: 'http://www.aarambh.org/images/logo.jpg'
            },
            donateFTUE: {
                title: 'Donate napkins by tabbing',
                info: 'somestuff about donation'
            },
            weeklyTargetTabs: 250,
            unitString: '51 napkins',
            daysLeft: 1
        },
        dailyImage: 'http://res.cloudinary.com/epicfoundation/image/upload/c_scale,h_1100/v1515774704/unsplash/paul-gilmore-260937_vgncso.jpg'
    },
    chooselol: {
        projects: [{
                projectId: 'project-helpdesk',
                projectTitle: 'Helpdesks',
                isFeatured: false,
                showcasePhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT55IEoispK7mRRkBkQrblJRWWQBuFCPevVGA12QitxjVUg_zKN_g',
                ngoId: 'aarambh',
                featureActionTitle: 'Build School Helpdesks',
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957196/Artboard_2_3x_fv3di4.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031005/UI%20images/AARAMBH_Small_1_2x.png',
                actionTitle: 'Build<br>School<br>Helpdesks',
                cardStyle: 'background: radial-gradient(circle, #542A1A 0%, #301409 100%); color:white',
                homeDescription: 'Aarambh stuffff sdfdfsdf dlkjfsdlfjd lsjs dfkjsdlf is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting hea . . .',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
                unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957194/aarambh_3x_nmwmwl.png',
                currentUnits: 5,
                currentUnitMeasure: 'desk',
                donateThanks: 'Thanks for helping Aarambh reach out to 1434 children',
                conversionFormula: '/119',
                donateFTUE: [Object],
                ngo: [Object],
                weeklyTargetTabs: 250,
                unitString: '5 desks'
            },
            {
                projectId: 'project-tbs',
                projectTitle: 'Tarun Bharat Sangh',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031037/UI%20images/TBH_Small_1_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031037/UI%20images/TBH_Small_1_2x.png',
                showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                ngoId: 'tbs',
                featureActionTitle: 'Help Rajasthan With Water',
                actionTitle: 'Help<br>Rajasthan<br>With Water',
                homeDescription: 'Waterman is dfsdff fdsfd fsfslhlks an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled b . . .',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 12,
                donateThanks: 'Thanks for helping TBS make water!',
                cardStyle: 'background: radial-gradient(circle, #FFFFFF 0%, #FFFFFF 71.54%, #EEEEEE 100%); color:black',
                conversionFormula: '/100',
                currentUnitMeasure: 'project',
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                ngo: [Object],
                unitString: '12 projects'
            },
            {
                projectId: 'project-hhk',
                projectTitle: 'HHK',
                isFeatured: true,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Big_1_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
                showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
                ngoId: 'hhk',
                featureActionTitle: 'Create Eco-friend Sanitary-pads',
                actionTitle: 'Create<br>Eco-friendly<br>Sanitary-pads',
                cardStyle: 'background: linear-gradient(254.64deg, #FFEEF7 0%, #FFCAE5 100%); color:black',
                homeDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with . . .',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 51,
                donateThanks: 'Thanks for helping women women reach out to 1434 villagers',
                conversionFormula: '/0.7',
                currentUnitMeasure: 'napkin',
                ngo: {
                    ngoName: 'HHK',
                    ngoUrl: 'http://www.aarambh.org/',
                    ngoPhotoUrl: 'http://www.aarambh.org/images/logo.jpg'
                },
                donateFTUE: {
                    title: 'Donate napkins by tabbing',
                    info: 'somestuff about donation'
                },
                weeklyTargetTabs: 250,
                unitString: '51 napkins',
                daysLeft: 1
            }
        ],
        featuredProject: {
            projectId: 'project-lol',
            projectTitle: 'Liter of Light',
            isFeatured: false,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031026/UI%20images/LOL_Big_1_2x.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031025/UI%20images/LOL_Small_1_Copy_2_2x.png',
            showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            ngoId: 'lol',
            featureActionTitle: 'Provide Buld Lights',
            actionTitle: 'Provide<br>Bulb<br>Lights',
            cardStyle: 'background:black;color:white',
            homeDescription: 'Liter of lights sdfdslkjdf skdjfdklsfj) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and di . . .',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 2,
            conversionFormula: '/50',
            donateThanks: 'Thanks for helping LOL reach out to 1434 villagers',
            currentUnitMeasure: 'lamp',
            donateFTUE: [Object],
            weeklyTargetTabs: 250,
            ngo: [Object],
            unitString: '2 lamps'
        },
        dailyImage: 'http://res.cloudinary.com/epicfoundation/image/upload/c_scale,h_1100/v1515774704/unsplash/paul-gilmore-260937_vgncso.jpg'
    },
    chooseaar: {
        projects: [{
                projectId: 'project-tbs',
                projectTitle: 'Tarun Bharat Sangh',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031037/UI%20images/TBH_Small_1_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031037/UI%20images/TBH_Small_1_2x.png',
                showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                ngoId: 'tbs',
                featureActionTitle: 'Help Rajasthan With Water',
                actionTitle: 'Help<br>Rajasthan<br>With Water',
                homeDescription: 'Waterman is dfsdff fdsfd fsfslhlks an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled b . . .',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 12,
                donateThanks: 'Thanks for helping TBS make water!',
                cardStyle: 'background: radial-gradient(circle, #FFFFFF 0%, #FFFFFF 71.54%, #EEEEEE 100%); color:black',
                conversionFormula: '/100',
                currentUnitMeasure: 'project',
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                ngo: [Object],
                unitString: '12 projects'
            },
            {
                projectId: 'project-hhk',
                projectTitle: 'HHK',
                isFeatured: true,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Big_1_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
                showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
                ngoId: 'hhk',
                featureActionTitle: 'Create Eco-friend Sanitary-pads',
                actionTitle: 'Create<br>Eco-friendly<br>Sanitary-pads',
                cardStyle: 'background: linear-gradient(254.64deg, #FFEEF7 0%, #FFCAE5 100%); color:black',
                homeDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with . . .',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 51,
                donateThanks: 'Thanks for helping women women reach out to 1434 villagers',
                conversionFormula: '/0.7',
                currentUnitMeasure: 'napkin',
                ngo: {
                    ngoName: 'HHK',
                    ngoUrl: 'http://www.aarambh.org/',
                    ngoPhotoUrl: 'http://www.aarambh.org/images/logo.jpg'
                },
                donateFTUE: {
                    title: 'Donate napkins by tabbing',
                    info: 'somestuff about donation'
                },
                weeklyTargetTabs: 250,
                unitString: '51 napkins',
                daysLeft: 1
            }, {
                projectId: 'project-lol',
                projectTitle: 'Liter of Light',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031026/UI%20images/LOL_Big_1_2x.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031025/UI%20images/LOL_Small_1_Copy_2_2x.png',
                showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                ngoId: 'lol',
                featureActionTitle: 'Provide Buld Lights',
                actionTitle: 'Provide<br>Bulb<br>Lights',
                cardStyle: 'background:black;color:white',
                homeDescription: 'Liter of lights sdfdslkjdf skdjfdklsfj) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and di . . .',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 2,
                conversionFormula: '/50',
                donateThanks: 'Thanks for helping LOL reach out to 1434 villagers',
                currentUnitMeasure: 'lamp',
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                ngo: [Object],
                unitString: '2 lamps'
            }
        ],
        featuredProject: {
            projectId: 'project-helpdesk',
            projectTitle: 'Helpdesks',
            isFeatured: false,
            showcasePhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT55IEoispK7mRRkBkQrblJRWWQBuFCPevVGA12QitxjVUg_zKN_g',
            ngoId: 'aarambh',
            featureActionTitle: 'Build School Helpdesks',
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957196/Artboard_2_3x_fv3di4.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031005/UI%20images/AARAMBH_Small_1_2x.png',
            actionTitle: 'Build<br>School<br>Helpdesks',
            cardStyle: 'background: radial-gradient(circle, #542A1A 0%, #301409 100%); color:white',
            homeDescription: 'Aarambh stuffff sdfdfsdf dlkjfsdlfjd lsjs dfkjsdlf is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting hea . . .',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
            unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957194/aarambh_3x_nmwmwl.png',
            currentUnits: 5,
            currentUnitMeasure: 'desk',
            donateThanks: 'Thanks for helping Aarambh reach out to 1434 children',
            conversionFormula: '/119',
            donateFTUE: [Object],
            ngo: [Object],
            weeklyTargetTabs: 250,
            unitString: '5 desks'
        },
        dailyImage: 'http://res.cloudinary.com/epicfoundation/image/upload/c_scale,h_1100/v1515774704/unsplash/paul-gilmore-260937_vgncso.jpg'
    },
    choosetbs: {
        projects: [{
            projectId: 'project-hhk',
            projectTitle: 'HHK',
            isFeatured: true,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Big_1_2x.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
            showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
            ngoId: 'hhk',
            featureActionTitle: 'Create Eco-friend Sanitary-pads',
            actionTitle: 'Create<br>Eco-friendly<br>Sanitary-pads',
            cardStyle: 'background: linear-gradient(254.64deg, #FFEEF7 0%, #FFCAE5 100%); color:black',
            homeDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with . . .',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 51,
            donateThanks: 'Thanks for helping women women reach out to 1434 villagers',
            conversionFormula: '/0.7',
            currentUnitMeasure: 'napkin',
            ngo: {
                ngoName: 'HHK',
                ngoUrl: 'http://www.aarambh.org/',
                ngoPhotoUrl: 'http://www.aarambh.org/images/logo.jpg'
            },
            donateFTUE: {
                title: 'Donate napkins by tabbing',
                info: 'somestuff about donation'
            },
            weeklyTargetTabs: 250,
            unitString: '51 napkins',
            daysLeft: 1
        }, {
            projectId: 'project-lol',
            projectTitle: 'Liter of Light',
            isFeatured: false,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031026/UI%20images/LOL_Big_1_2x.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031025/UI%20images/LOL_Small_1_Copy_2_2x.png',
            showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            ngoId: 'lol',
            featureActionTitle: 'Provide Buld Lights',
            actionTitle: 'Provide<br>Bulb<br>Lights',
            cardStyle: 'background:black;color:white',
            homeDescription: 'Liter of lights sdfdslkjdf skdjfdklsfj) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and di . . .',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 2,
            conversionFormula: '/50',
            donateThanks: 'Thanks for helping LOL reach out to 1434 villagers',
            currentUnitMeasure: 'lamp',
            donateFTUE: [Object],
            weeklyTargetTabs: 250,
            ngo: [Object],
            unitString: '2 lamps'
        }, {
            projectId: 'project-helpdesk',
            projectTitle: 'Helpdesks',
            isFeatured: false,
            showcasePhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT55IEoispK7mRRkBkQrblJRWWQBuFCPevVGA12QitxjVUg_zKN_g',
            ngoId: 'aarambh',
            featureActionTitle: 'Build School Helpdesks',
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957196/Artboard_2_3x_fv3di4.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031005/UI%20images/AARAMBH_Small_1_2x.png',
            actionTitle: 'Build<br>School<br>Helpdesks',
            cardStyle: 'background: radial-gradient(circle, #542A1A 0%, #301409 100%); color:white',
            homeDescription: 'Aarambh stuffff sdfdfsdf dlkjfsdlfjd lsjs dfkjsdlf is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting hea . . .',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
            unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957194/aarambh_3x_nmwmwl.png',
            currentUnits: 5,
            currentUnitMeasure: 'desk',
            donateThanks: 'Thanks for helping Aarambh reach out to 1434 children',
            conversionFormula: '/119',
            donateFTUE: [Object],
            ngo: [Object],
            weeklyTargetTabs: 250,
            unitString: '5 desks'
        }],
        featuredProject: {
            projectId: 'project-tbs',
            projectTitle: 'Tarun Bharat Sangh',
            isFeatured: false,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031037/UI%20images/TBH_Small_1_2x.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031037/UI%20images/TBH_Small_1_2x.png',
            showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            ngoId: 'tbs',
            featureActionTitle: 'Help Rajasthan With Water',
            actionTitle: 'Help<br>Rajasthan<br>With Water',
            homeDescription: 'Waterman is dfsdff fdsfd fsfslhlks an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled b . . .',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding . . .',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 12,
            donateThanks: 'Thanks for helping TBS make water!',
            cardStyle: 'background: radial-gradient(circle, #FFFFFF 0%, #FFFFFF 71.54%, #EEEEEE 100%); color:black',
            conversionFormula: '/100',
            currentUnitMeasure: 'project',
            donateFTUE: [Object],
            weeklyTargetTabs: 250,
            ngo: [Object],
            unitString: '12 projects'
        },
        dailyImage: 'http://res.cloudinary.com/epicfoundation/image/upload/c_scale,h_1100/v1515774704/unsplash/paul-gilmore-260937_vgncso.jpg'
    },
    login: {
        stats: { donations: 'Rs. 11,065', followers: 3 },
        projects: [{
                projectId: 'project-helpdesk',
                projectTitle: 'Helpdesks',
                isFeatured: false,
                showcasePhoto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT55IEoispK7mRRkBkQrblJRWWQBuFCPevVGA12QitxjVUg_zKN_g',
                ngoId: 'aarambh',
                featureActionTitle: 'Build School Helpdesks',
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957196/Artboard_2_3x_fv3di4.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/c_crop,h_740/v1523957953/Artboard_2_3x_t1zbqi.png',
                actionTitle: 'Build<br>School<br>Helpdesks',
                homeDescription: 'Aarambh stuffff sdfdfsdf dlkjfsdlfjd lsjs dfkjsdlf is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such means during menstruation which are potentially harmful.',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggarstowards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such means during menstruation which are potentially harmful.',
                unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957194/aarambh_3x_nmwmwl.png',
                currentUnits: 5,
                currentUnitMeasure: 'desk',
                donateThanks: 'Thanks for helping Aarambh reach out to 1434 children',
                conversionFormula: '/119',
                donateFTUE: [Object],
                ngo: [Object],
                weeklyTargetTabs: 250,
                unitString: '5 desks'
            },
            {
                projectId: 'project-hhk',
                projectTitle: 'HHK',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523498950/Artboard_2_hcz8kb.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/c_crop,h_740/v1523957184/HHK1_3x_a80oct.png',
                showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                ngoId: 'hhk',
                featureActionTitle: 'Create Eco-friend Sanitary-pads',
                actionTitle: 'Create<br>Eco-friendly<br>Sanitary-pads',
                homeDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such means during menstruation which are potentially harmful.',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggarstowards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such means during menstruation which are potentially harmful.',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 51,
                donateThanks: 'Thanks for helping women women reach out to 1434 villagers',
                conversionFormula: '/0.7',
                currentUnitMeasure: 'napkin',
                ngo: [Object],
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                unitString: '51 napkins'
            },
            {
                projectId: 'project-lol',
                projectTitle: 'Liter of Light',
                isFeatured: false,
                primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523499284/Artboard_2_hcz8kb.png',
                secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/c_crop,h_740/v1523499284/Artboard_2_hcz8kb.png',
                showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                ngoId: 'lol',
                featureActionTitle: 'Provide Buld Lights',
                actionTitle: 'Provide<br>Bulb<br>Lights',
                homeDescription: 'Liter of lights sdfdslkjdf skdjfdklsfj) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfareschemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use clothor other such means during menstruation which are potentially harmful.',
                shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggarstowards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such means during menstruation which are potentially harmful.',
                unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
                currentUnits: 2,
                conversionFormula: '/50',
                donateThanks: 'Thanks for helping LOL reach out to 1434 villagers',
                currentUnitMeasure: 'lamp',
                donateFTUE: [Object],
                weeklyTargetTabs: 250,
                ngo: [Object],
                unitString: '2 lamps'
            }
        ],
        featuredProject: {
            projectId: 'project-tbs',
            projectTitle: 'Tarun Bharat Sangh',
            isFeatured: true,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523771594/TBH_2_emxbyv.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957647/aaaq_yww14i.png',
            showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            ngoId: 'tbs',
            featureActionTitle: 'Help Rajasthan With Water',
            actionTitle: 'Help<br>Rajasthan<br>With Water',
            homeDescription: 'Waterman is dfsdff fdsfd fsfslhlks an NGO whose primary mission is to create awareness against begging, molding childbeggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such means during menstruation which are potentially harmful.',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such meansduring menstruation which are potentially harmful.',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 12,
            donateThanks: 'Thanks for helping TBS make water!',
            conversionFormula: '/100',
            currentUnitMeasure: 'project',
            donateFTUE: {
                title: 'Donate water by tabbing',
                info: 'somestuff about donation'
            },
            weeklyTargetTabs: 250,
            ngo: {
                ngoName: 'TBS',
                ngoUrl: 'http://www.aarambh.org/',
                ngoPhotoUrl: 'http://www.aarambh.org/images/logo.jpg'
            },
            unitString: '12 projects'
        }
    },
    newtab: {
        stats: {
            donations: 'Rs. 11,065',
            remainingTime: '13 days ',
            shortRemaining: '13d'
        },
        user: {
            progress: 8.8,

            picture: 'https://lh4.googleusercontent.com/-4LgLFjwVpeQ/AAAAAAAAAAI/AAAAAAAAA3k/ktebr6TpI3I/photo.jpg?sz=50',
            color_theme: 'unsplash',
            user_id: 'user1519531262490',
            state: 'v1_week_ongoing',
            web_version: '0.0.1',
            timestamp: 1519531262490,
            email: 'mallikapriyak@gmail.com',
            name: 'Mallika',
            google_token: 'ya29.GlttBVynX-VlqrB0DmPTJIcOsTtxdq57kgcICH96mimqOtaaQKS6lCVSXpvft-3k3coDBf8XJe9-BYcr7w41UiYttUEEiVPfVqsfNH4ENYgfCm5_-ic69yK2ndmI',
            google_id: '112430514351332325676',
            __v: 22,
            modified_timestamp: 1524140643215,
            total_tabs: 527,
            project: {
                project_id: 'project-tbs',
                target_end_time: 1525350135390,
                target_start_time: 1524140535390,
                tabs: 22
            },
            all_project_donations: ['donation1523754083153',
                'donation1523754148729',
                'donation1523754215067',
                'donation1523754880198',
                'donation1523756102114',
                'donation1523756601578',
                'donation1523756905857',
                'donation1523771342376',
                'donation1523771877720',
                'donation1523874424927',
                'donation1523879594957',
                'donation1523879930026',
                'donation1523888648586',
                'donation1523893285404',
                'donation1523893739273',
                'donation1523894514349',
                'donation1523959667011',
                'donation1523959693432'
            ],
            hearts: {
                total_hearts: 639,
                current_cause_id: 'xyz',
                target_end_time: 1523750688818,
                target_start_time: 1523750688818,
                current_week_hearts: 36,
                donations_till_date: []
            },
            last_project: { tabs: '5', project_id: 'project-hhk' },
            previous_donation: { previous_cause_id: 'xyz', previous_week_hearts: '6' },
            ui_settings: { app_bar: true, search_visible: true }
        },
        project: {
            projectId: 'project-tbs',
            projectTitle: 'Tarun Bharat Sangh',
            isFeatured: true,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523771594/TBH_2_emxbyv.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1523957647/aaaq_yww14i.png',
            showcasePhoto: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            ngoId: 'tbs',
            featureActionTitle: 'Help Rajasthan With Water',
            actionTitle: 'Help<br>Rajasthan<br>With Water',
            homeDescription: 'Waterman is dfsdff fdsfd fsfslhlks an NGO whose primary mission is to create awareness against begging, molding childbeggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such means during menstruation which are potentially harmful.',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such meansduring menstruation which are potentially harmful....',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 12,
            donateThanks: 'Thanks for helping TBS make water!',
            conversionFormula: '/100',
            currentUnitMeasure: 'project',
            donateFTUE: {
                title: 'Donate water by tabbing',
                info: 'somestuff about donation'
            },
            weeklyTargetTabs: 250,
            ngo: {
                ngoName: 'TBS',
                ngoUrl: 'http://www.aarambh.org/',
                ngoPhotoUrl: 'http://www.aarambh.org/images/logo.jpg'
            }
        },
        previousProjet: {},
        dailyImage: 'http://res.cloudinary.com/epicfoundation/image/upload/c_scale,h_1100/v1515774645/unsplash/unsplash3.jpg',
        showMissionSelectedPopup: false
    },
    newtabdonate: {
        stats: {
            donations: 'Rs. 11,066',
            remainingTime: '1 hour ',
            shortRemaining: '1s'
        },
        user: {
            progress: 2,

            picture: 'https://lh4.googleusercontent.com/-4LgLFjwVpeQ/AAAAAAAAAAI/AAAAAAAAA3k/ktebr6TpI3I/photo.jpg?sz=50',
            color_theme: 'unsplash',
            user_id: 'user1519531262490',
            state: 'v1_donate_pending',
            web_version: '0.0.1',
            timestamp: 1519531262490,
            email: 'mallikapriyak@gmail.com',
            name: 'Mallika',
            google_token: 'ya29.GlttBVynX-VlqrB0DmPTJIcOsTtxdq57kgcICH96mimqOtaaQKS6lCVSXpvft-3k3coDBf8XJe9-BYcr7w41UiYttUEEiVPfVqsfNH4ENYgfCm5_-ic69yK2ndmI',
            google_id: '112430514351332325676',
            __v: 24,
            modified_timestamp: 1524260224443,
            total_tabs: 575,
            project: {
                project_id: 'project-hhk',
                target_end_time: 1524247693313,
                target_start_time: 1524247693313,
                tabs: 5
            },
            all_project_donations: ['donation1523754083153',
                'donation1523754148729',
                'donation1523754215067',
                'donation1523754880198',
                'donation1523756102114',
                'donation1523756601578',
                'donation1523756905857',
                'donation1523771342376',
                'donation1523771877720',
                'donation1523874424927',
                'donation1523879594957',
                'donation1523879930026',
                'donation1523888648586',
                'donation1523893285404',
                'donation1523893739273',
                'donation1523894514349',
                'donation1523959667011',
                'donation1523959693432',
                'donation1524208258652',
                'donation1524253070921'
            ],
            hearts: {
                total_hearts: 639,
                current_cause_id: 'xyz',
                target_end_time: 1523750688818,
                target_start_time: 1523750688818,
                current_week_hearts: 36,
                donations_till_date: []
            },
            last_project: { tabs: '8', project_id: 'project-hhk' },
            previous_donation: { previous_cause_id: 'xyz', previous_week_hearts: '6' },
            ui_settings: { app_bar: true, search_visible: true }
        },
        project: {
            projectId: 'project-hhk',
            projectTitle: 'HHK',
            isFeatured: true,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Big_1_2x.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
            showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031014/UI%20images/HHK_Small_1_2x.png',
            ngoId: 'hhk',
            featureActionTitle: 'Create Eco-friend Sanitary-pads',
            actionTitle: 'Create<br>Eco-friendly<br>Sanitary-pads',
            cardStyle: 'background: linear-gradient(254.64deg, #FFEEF7 0%, #FFCAE5 100%); color:black',
            homeDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such means during menstruation which are potentially harmful.',
            shortDescription: 'Har Hath Kalam (HHK) is an NGO whose primary mission is to create awareness against begging, molding child beggars towards by providing them with education, assisting healthy and disabled beggars with employment opportunities and welfare schemes and so on.<br><br>During some such drives in slums and villages, Ruhpreet a volunteer at HHK noticed that many women still use cloth or other such meansduring menstruation which are potentially harmful. . . .',
            unitIcon: 'https://assets.awwwards.com/awards/media/cache/thumb_834_598/external/2017/06/5953d73168ad9.jpg',
            currentUnits: 51,
            donateThanks: 'Thanks for helping women women reach out to 1434 villagers',
            conversionFormula: '/0.7',
            currentUnitMeasure: 'napkin',
            ngo: {
                ngoName: 'HHK',
                ngoUrl: 'http://www.aarambh.org/',
                ngoPhotoUrl: 'http://www.aarambh.org/images/logo.jpg'
            },
            donateFTUE: {
                title: 'Donate napkins by tabbing',
                info: 'somestuff about donation'
            },
            weeklyTargetTabs: 250,
            unitsCreated: '8.1',
            unitrep: 'napkins'
        },
        previousProjet: {},
        dailyImage: 'http://res.cloudinary.com/epicfoundation/image/upload/c_scale,h_1100/v1515771774/mtn1.jpg',
        showMissionSelectedPopup: false
    },
    projectlol: {
        details: {
            projectId: 'project-lol',
            isFeatured: false,
            primaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031026/UI%20images/LOL_Big_1_2x.png',
            secondaryMissionPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031025/UI%20images/LOL_Small_1_Copy_2_2x.png',
            showcasePhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524391821/UI%20images/LOL_squaere_3x.png',
            ngoId: 'lol',
            fullFeaturePhoto: 'https://res.cloudinary.com/epicfoundation/image/upload/v1523669576/dfd_gzbont.jpg',
            cardStyle: 'background:black;color:white',
            unitIcon: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524391724/UI%20images/LOL_tiny.png',
            conversionFormula: '/50',
            tabsForSingleUnit: 200,
            forByLine: 'For 2100 Families',
            projectTitle: 'Light Rural Homes',
            featureActionTitle: 'Light Rural Homes',
            actionTitle: 'Light<br>Rural<br>Homes',
            homeDescription: 'Even today, over 240 million Indians do not have access to electricity. Several Government programs tried to address the issue, but a large number vulnerable, poor citizens of the country still have received little to no relief to their woes. Liter of Light Bangalore chapter is providing such households access to low cost, solar eco-friendly bottle bulbs. These solar powered bulbs provide illumination even during the night. Till date, it has illuminated over 2000 homes across India. Flutur has partnered with Liter of Light Bangalore chapter to illuminate one home at a time.',
            shortDescription: 'Over 240 million Indias do not have access to electricity. Liter of Light Bangalore chapter is providing such households access to low cost, solar eco-friendly bottle bulbs. These solar powered bulbs provide illumination even during the night. . . .',
            playPhoto: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524031695/UI%20images/LOL_play_1_2x.png',
            donateThanks: 'Thanks for helping LOL reach out to 1434 villagers',
            currentUnitMeasure: 'lamp',
            autoActionMessage: 'sdasd sdsad sd asd sd adadad dsad d',
            donateFTUE: {
                title: 'Donate light by tabbing',
                info: 'somestuff about donation long long dsfsfs dfsdlfjdf sdfk jd sdfdslkj dsf lkfjsdfkj'
            },
            weeklyTargetTabs: 250,
            ngo: {
                ngoName: 'Liter of Light',
                ngoUrl: 'http://www.literoflightusa.org/home/',
                ngoPhotoUrl: 'http://res.cloudinary.com/epicfoundation/image/upload/v1524396352/UI%20images/LOL_logo_2x.png'
            }
        },
        currUnits: '121',
        stats: { donations: 'Rs. 11,134', followers: 6 }
    }
};
module.exports = Constants;